sumSalary function added
js-tasks-ru/jsbasic-20220419-2_annrd9 pull request #3
Opened 2022-04-25 15:41 UTC by AnnRd

Реализация функции суммирования зарплат из объекта.

2022-04-25 15:41 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2022-04-25 15:45 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2022-04-25 15:54 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2022-04-25 17:39 UTC, koalex requested changes
Несмотря на то, что тесты проходят успешно, нужно исправить замечание в **2-3**

2022-04-25 17:39 UTC, koalex commented on 2-module/3-task/index.js
> +    calculator.b = b;
Здесь тоже должно быть `this.a` и `this.b`. Исправить

2022-04-26 07:51 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2022-04-27 07:41 UTC, koalex approved these changes

2022-04-27 07:42 UTC, merged